-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."stations_metadata_fetch" add column "order" integer
--  not null default '1';
