# Generated by Django 5.1.11 on 2025-07-21 23:29

import django.db.models.deletion
import superapp.apps.backups.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('all_models', 'All Models'), ('essential_data', 'Essential Data')], default='all_models', max_length=50, verbose_name='Backup Type')),
                ('file', models.FileField(blank=True, null=True, storage=superapp.apps.backups.storage.PrivateBackupStorage, upload_to='backups/', verbose_name='File')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, storage=superapp.apps.backups.storage.PrivateBackupStorage, upload_to='restores/', verbose_name='File')),
                ('type', models.CharField(choices=[('all_models', 'All Models'), ('essential_data', 'Essential Data')], default='all_models', max_length=50, verbose_name='Restore Type')),
                ('cleanup_existing_data', models.BooleanField(default=True, verbose_name='Cleanup existing data')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('backup', models.ForeignKey(blank=True, help_text='Optional. If selected, backup file path will override the file field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='backups.backup', verbose_name='Backup')),
            ],
            options={
                'verbose_name': 'Restore',
                'verbose_name_plural': 'Restores',
                'ordering': ['-created_at'],
            },
        ),
    ]
