# Generated by Django 5.1.11 on 2025-07-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restore',
            name='cleanup_existing_data',
            field=models.BooleanField(default=False, verbose_name='Cleanup existing data'),
        ),
    ]
