# Generated by Django 5.1.9 on 2025-05-22 09:26

import superapp.apps.backups.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FileField(blank=True, null=True, storage=superapp.apps.backups.storage.PrivateBackupStorage, upload_to='backups/', verbose_name='File'),
        ),
    ]
