# Generated by Django 5.1.9 on 2025-05-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_backup_finished_at_backup_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='type',
            field=models.CharField(choices=[('all_models', 'All Models')], default='all_models', max_length=50, verbose_name='Backup Type'),
        ),
    ]
