# Generated by Django 5.1.9 on 2025-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_backup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='type',
            field=models.CharField(choices=[('easywindows_common_models', 'Easywindows Common models'), ('easywindows_organization', 'Easywindows Organization models'), ('all_models', 'All Models'), ('users', 'Users')], default='all_models', max_length=50, verbose_name='Backup Type'),
        ),
    ]
