# Generated by Django 5.1.9 on 2025-05-22 10:41

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0005_backup_name_alter_backup_type'),
        ('easywindow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='easywindow.organization'),
        ),
    ]
