# Generated by Django 5.1.9 on 2025-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0007_restore'),
    ]

    operations = [
        migrations.AddField(
            model_name='restore',
            name='cleanup_existing_data',
            field=models.BooleanField(default=True, verbose_name='Cleanup existing data'),
        ),
        migrations.AddField(
            model_name='restore',
            name='exclude_models',
            field=models.JSONField(default=list, verbose_name='Exclude models'),
        ),
    ]
