# Generated by Django 5.1.9 on 2025-05-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0009_remove_restore_exclude_models_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restore',
            name='exclude_models_from_import',
        ),
        migrations.AddField(
            model_name='restore',
            name='type',
            field=models.CharField(choices=[('easywindows_common_models', 'Easywindows Common models'), ('easywindows_organization', 'Easywindows Organization models'), ('all_models', 'All Models'), ('users', 'Users')], default='all_models', max_length=50, verbose_name='Backup Type'),
        ),
    ]
