# Generated by Django 5.1.9 on 2025-05-22 13:13

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0010_remove_restore_exclude_models_from_import_and_more'),
        ('easywindow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='easywindow.organization'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='tenant',
            field=django_multitenant.fields.TenantForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='easywindow.organization'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='type',
            field=models.CharField(choices=[('easywindows_common_models', 'Easywindows Common models'), ('easywindows_organization', 'Easywindows Organization models'), ('all_models', 'All Models'), ('users', 'Users')], default='all_models', max_length=50, verbose_name='Restore Type'),
        ),
    ]
