# Generated by Django 5.1.8 on 2025-04-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_checkout_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_dashboard', 'Can view dashboard'), ('can_view_custom_page', 'Can view custom page'), ('is_normal_user', 'Is a normal user?')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
