-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."station_to_station_group" add column "order" integer
--  null default '0';
