services:
  postgres:
    image: timescale/timescaledb-ha:pg16
    restart: unless-stopped
    shm_size: 2gb
    volumes:
      - db_data:/home/postgres/pgdata/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "100m" # file size
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --notify-keyspace-events Exe
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    volumes:
      - .:/app:delegated
      - /app/__pycache__
      - /app/**/__pycache__
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: /app/scripts/run-server.sh
  priority-worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - "postgres"
      - "redis"
    volumes:
      - .:/app:delegated
      - /app/__pycache__
      - /app/**/__pycache__
    env_file:
      - .env
    command: ./scripts/run-priority-worker.sh
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "[c]elery -A superapp worker"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - "postgres"
      - "redis"
    volumes:
      - .:/app:delegated
      - /app/__pycache__
      - /app/**/__pycache__
    env_file:
      - .env
    command: ./scripts/run-worker.sh
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "[c]elery -A superapp worker"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
volumes:
  db_data:
  redis:
