version: '3.6'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    ports:
      - "8543:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  auth:
    build:
      context: ./auth
    depends_on:
      - graphql-engine
    restart: unless-stopped
    ports:
      - "8086:8080"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  app:
    build:
      context: ./app
    depends_on:
      - graphql-engine
    restart: unless-stopped
    ports:
      - "8085:8080"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  admin:
    build:
      context: ./admin
    ports:
      - "8545:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  graphql-engine:
    image: hasura/graphql-engine:v2.33.4.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  tor-proxy:
    image: dperson/torproxy
    ports:
      - "9050:9050"
    restart: unless-stopped
    environment:
      LOCATION: DE
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
volumes:
  db_data:
