-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."stations" add column "generate_hls_stream" boolean
--  not null default 'true';
