-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP FUNCTION IF EXISTS radio_crestion_listeners(station_row stations);
-- CREATE FUNCTION radio_crestion_listeners(station_row stations)
-- RETURNS INT AS $$
--   SELECT COUNT(*) FROM listening_events WHERE station_id=station_row.id AND timestamp > NOW() - '1 minute'::interval;
-- $$ LANGUAGE sql STABLE;
