export const PROJECT_ENV: {
  FRONTEND_SERVER_PORT: number
  FRONTEND_GRAPHQL_ENDPOINT_URI: string
} = {
  FRONTEND_SERVER_PORT: parseInt(process.env.FRONTEND_SERVER_PORT || "3000"),
  FRONTEND_GRAPHQL_ENDPOINT_URI: process.env.FRONTEND_GRAPHQL_ENDPOINT_URI || "",
}
