export const PROJECT_ENV: {
  FRONTEND_SERVER_PORT: number
  FRONTEND_GRAPHQL_INTERNAL_ENDPOINT_URI: string
  FRONTEND_GRAPHQL_INTERNAL_ENDPOINT_ADMIN_SECRET: string
  FRONTEND_COOKIE_SECRET: string
  FRONTEND_CDN_PREFIX: string
} = {
  FRONTEND_SERVER_PORT: parseInt(process.env.FRONTEND_SERVER_PORT || "3000"),
  FRONTEND_GRAPHQL_INTERNAL_ENDPOINT_URI: process.env.FRONTEND_GRAPHQL_INTERNAL_ENDPOINT_URI || "",
  FRONTEND_GRAPHQL_INTERNAL_ENDPOINT_ADMIN_SECRET: process.env.FRONTEND_GRAPHQL_INTERNAL_ENDPOINT_ADMIN_SECRET || "",
  FRONTEND_COOKIE_SECRET: process.env.FRONTEND_COOKIE_SECRET || "",
  FRONTEND_CDN_PREFIX: process.env.FRONTEND_CDN_PREFIX || "",
}
