# Generated by Django 5.1.11 on 2025-07-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0005_fix_duplicate_foreign_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('anonymous_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='Anonymous ID')),
                ('anonymous_id_verified', models.DateTimeField(blank=True, null=True, verbose_name='Anonymous ID verified')),
                ('email_verified', models.DateTimeField(blank=True, null=True, verbose_name='Email verified')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number')),
                ('phone_number_verified', models.DateTimeField(blank=True, null=True, verbose_name='Phone number verified')),
                ('checkout_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Checkout phone number')),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='listeningevents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_events', to='radio_crestin.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_reviews', to='radio_crestin.users', verbose_name='User'),
        ),
    ]
