# Generated by Django 5.1.11 on 2025-07-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0007_alter_songs_unique_together_alter_songs_artist_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Drop existing foreign key constraints
            ALTER TABLE stations_now_playing 
            DROP CONSTRAINT IF EXISTS stations_now_playing_song_id_fkey;
            
            -- Recreate constraint with SET NULL on DELETE and TRUNCATE-compatible behavior
            ALTER TABLE stations_now_playing 
            ADD CONSTRAINT stations_now_playing_song_id_fkey 
            FOREIGN KEY (song_id) REFERENCES songs(id) 
            ON DELETE SET NULL 
            DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
            -- Restore original constraint
            ALTER TABLE stations_now_playing 
            DROP CONSTRAINT IF EXISTS stations_now_playing_song_id_fkey;
            
            ALTER TABLE stations_now_playing 
            ADD CONSTRAINT stations_now_playing_song_id_fkey 
            FOREIGN KEY (song_id) REFERENCES songs(id) 
            ON DELETE SET NULL;
            """
        ),
    ]
