# Generated by Django 5.1.11 on 2025-07-21 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0011_stations_check_uptime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listeningevents',
            options={'managed': True, 'ordering': ('-created_at',), 'verbose_name': 'Listening Event (Legacy)', 'verbose_name_plural': 'Listening Events (Legacy)'},
        ),
        migrations.AlterField(
            model_name='appusers',
            name='anonymous_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='anonymous_id_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='checkout_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='email_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='phone_number_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ListeningSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('anonymous_session_id', models.CharField(help_text='Anonymous session identifier from NGINX logs', max_length=512, verbose_name='Anonymous Session ID')),
                ('start_time', models.DateTimeField(verbose_name='Session start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Session end time')),
                ('last_activity', models.DateTimeField(help_text='Last time user activity was detected', verbose_name='Last activity')),
                ('duration_seconds', models.IntegerField(default=0, help_text='Total session duration based on last_activity - start_time', verbose_name='Duration in seconds')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Total requests')),
                ('bytes_transferred', models.BigIntegerField(default=0, verbose_name='Bytes transferred')),
                ('playlist_requests', models.IntegerField(default=0, verbose_name='Playlist requests')),
                ('segment_requests', models.IntegerField(default=0, verbose_name='Segment requests')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Referer')),
                ('is_active', models.BooleanField(default=True, help_text='True if session had activity in the last 5 minutes', verbose_name='Is active')),
                ('info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='radio_crestin.stations', verbose_name='Station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='radio_crestin.appusers', verbose_name='App Users')),
            ],
            options={
                'verbose_name': 'Listening Session',
                'verbose_name_plural': 'Listening Sessions',
                'db_table': 'listening_sessions',
                'ordering': ('-last_activity',),
                'managed': True,
                'indexes': [models.Index(fields=['station', 'is_active', 'last_activity'], name='listening_s_station_09763c_idx'), models.Index(fields=['user', 'station', 'last_activity'], name='listening_s_user_id_b34cee_idx'), models.Index(fields=['anonymous_session_id', 'station'], name='listening_s_anonymo_9ec6ab_idx'), models.Index(fields=['is_active', 'last_activity'], name='listening_s_is_acti_e43d26_idx')],
            },
        ),
    ]
