# Generated by Django 5.1.11 on 2025-07-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0012_alter_listeningevents_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListeningEvents',
        ),
    ]
