# Generated by Django 5.1.11 on 2025-07-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0013_delete_listeningevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningsessions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='radio_crestin.appusers', verbose_name='App Users'),
        ),
    ]
