# Generated by Django 5.1.11 on 2025-07-29 19:01

import regex_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0014_make_user_nullable_in_listening_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationsmetadatafetch',
            name='artist_regex',
            field=regex_field.fields.RegexField(blank=True, help_text='Regex pattern to extract artist (optional)', max_length=500, null=True, verbose_name='Artist Regex'),
        ),
        migrations.AlterField(
            model_name='stationsmetadatafetch',
            name='station_name_regex',
            field=regex_field.fields.RegexField(blank=True, help_text='Regex pattern to remove station name from title (optional)', max_length=500, null=True, verbose_name='Station Name Regex'),
        ),
        migrations.AlterField(
            model_name='stationsmetadatafetch',
            name='title_regex',
            field=regex_field.fields.RegexField(blank=True, help_text='Regex pattern to extract title (optional)', max_length=500, null=True, verbose_name='Title Regex'),
        ),
    ]
