# Generated by Django 5.1.2 on 2025-08-02

from django.db import migrations, models


def copy_station_order_to_new_order(apps, schema_editor):
    """Copy station_order values to the new order field, rounding to nearest integer."""
    Stations = apps.get_model('radio_crestin', 'Stations')
    
    for station in Stations.objects.all():
        station.order = round(station.station_order)
        station.save(update_fields=['order'])


def reverse_copy_order_to_station_order(apps, schema_editor):
    """Reverse operation: copy order back to station_order as float."""
    Stations = apps.get_model('radio_crestin', 'Stations')
    
    for station in Stations.objects.all():
        station.station_order = float(station.order)
        station.save(update_fields=['station_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0015_alter_stationsmetadatafetch_artist_regex_and_more'),
    ]

    operations = [
        # Step 1: Rename the existing order field to station_order
        migrations.RenameField(
            model_name='stations',
            old_name='order',
            new_name='station_order',
        ),
        # Step 2: Change station_order from IntegerField to FloatField
        migrations.AlterField(
            model_name='stations',
            name='station_order',
            field=models.FloatField(verbose_name='Station Order'),
        ),
        # Step 3: Add the new order field as IntegerField
        migrations.AddField(
            model_name='stations',
            name='order',
            field=models.IntegerField(verbose_name='Order', default=0),
            preserve_default=False,
        ),
        # Step 4: Copy data from station_order to order (rounded)
        migrations.RunPython(
            copy_station_order_to_new_order,
            reverse_copy_order_to_station_order
        ),
        # Step 5: Update the model meta ordering
        migrations.AlterModelOptions(
            name='stations',
            options={'managed': True, 'ordering': ('order', 'title'), 'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
    ]