# Generated by Django 5.1.2 on 2025-08-02

from django.db import migrations


def copy_station_order_to_order(apps, schema_editor):
    """Copy station_order values to order field, rounding to nearest integer."""
    Stations = apps.get_model('radio_crestin', 'Stations')
    
    for station in Stations.objects.all():
        station.order = round(station.station_order)
        station.save(update_fields=['order'])


def reverse_copy_order_to_station_order(apps, schema_editor):
    """Reverse operation: copy order back to station_order as float."""
    Stations = apps.get_model('radio_crestin', 'Stations')
    
    for station in Stations.objects.all():
        station.station_order = float(station.order)
        station.save(update_fields=['station_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0015_alter_stationsmetadatafetch_artist_regex_and_more'),
    ]

    operations = [
        migrations.RunPython(
            copy_station_order_to_order,
            reverse_copy_order_to_station_order
        ),
    ]