# Generated by Django 5.1.11 on 2025-08-02 17:54

from django.db import migrations, models


def copy_order_to_station_order(apps, schema_editor):
    Stations = apps.get_model('radio_crestin', 'Stations')
    for station in Stations.objects.all():
        station.station_order = station.order
        station.save(update_fields=['station_order'])


def reverse_copy_order(apps, schema_editor):
    Stations = apps.get_model('radio_crestin', 'Stations')
    for station in Stations.objects.all():
        station.station_order = 0
        station.save(update_fields=['station_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0015_alter_stationsmetadatafetch_artist_regex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='station_order',
            field=models.FloatField(default=0, verbose_name='Station Order'),
            preserve_default=False,
        ),
        migrations.RunPython(copy_order_to_station_order, reverse_copy_order),
    ]
