# Generated by Django 5.1.2 on 2025-08-02

from django.db import migrations, models


def copy_station_group_order_to_new_order(apps, schema_editor):
    """Copy station_group_order values to the new order field, rounding to nearest integer."""
    StationGroups = apps.get_model('radio_crestin', 'StationGroups')
    
    for group in StationGroups.objects.all():
        group.order = round(group.station_group_order)
        group.save(update_fields=['order'])


def reverse_copy_order_to_station_group_order(apps, schema_editor):
    """Reverse operation: copy order back to station_group_order as float."""
    StationGroups = apps.get_model('radio_crestin', 'StationGroups')
    
    for group in StationGroups.objects.all():
        group.station_group_order = float(group.order)
        group.save(update_fields=['station_group_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0016_copy_station_order_to_order'),
    ]

    operations = [
        # Step 1: Rename the existing order field to station_group_order
        migrations.RenameField(
            model_name='stationgroups',
            old_name='order',
            new_name='station_group_order',
        ),
        # Step 2: Change station_group_order from IntegerField to FloatField
        migrations.AlterField(
            model_name='stationgroups',
            name='station_group_order',
            field=models.FloatField(verbose_name='Station Group Order', default=0),
        ),
        # Step 3: Add the new order field as IntegerField
        migrations.AddField(
            model_name='stationgroups',
            name='order',
            field=models.IntegerField(verbose_name='Order', default=0),
        ),
        # Step 4: Copy data from station_group_order to order (rounded)
        migrations.RunPython(
            copy_station_group_order_to_new_order,
            reverse_copy_order_to_station_group_order
        ),
        # Step 5: Update the model meta ordering
        migrations.AlterModelOptions(
            name='stationgroups',
            options={'managed': True, 'ordering': ('station_group_order',), 'verbose_name': 'Station Group', 'verbose_name_plural': 'Station Groups'},
        ),
    ]