# Generated by Django 5.1.2 on 2025-08-02

from django.db import migrations


def copy_station_group_order_to_order(apps, schema_editor):
    """Copy station_group_order values to order field, rounding to nearest integer."""
    StationGroups = apps.get_model('radio_crestin', 'StationGroups')
    
    for group in StationGroups.objects.all():
        group.order = round(group.station_group_order)
        group.save(update_fields=['order'])


def reverse_copy_order_to_station_group_order(apps, schema_editor):
    """Reverse operation: copy order back to station_group_order as float."""
    StationGroups = apps.get_model('radio_crestin', 'StationGroups')
    
    for group in StationGroups.objects.all():
        group.station_group_order = float(group.order)
        group.save(update_fields=['station_group_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0016_copy_station_order_to_order'),
    ]

    operations = [
        migrations.RunPython(
            copy_station_group_order_to_order,
            reverse_copy_order_to_station_group_order
        ),
    ]