# Generated by Django 5.1.11 on 2025-08-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0017_copy_station_group_order_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='email',
            field=models.TextField(blank=True, default='', verbose_name='Email'),
        ),
    ]
