# Generated by Django 5.1.11 on 2025-08-02 17:58

from django.db import migrations, models


def copy_station_group_order_to_order(apps, schema_editor):
    StationGroups = apps.get_model('radio_crestin', 'StationGroups')
    for group in StationGroups.objects.all():
        group.order = round(group.station_group_order)
        group.save(update_fields=['order'])


def reverse_copy_order(apps, schema_editor):
    StationGroups = apps.get_model('radio_crestin', 'StationGroups')
    for group in StationGroups.objects.all():
        group.order = 0
        group.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0017_alter_stationgroups_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationgroups',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.RunPython(copy_station_group_order_to_order, reverse_copy_order),
    ]
