# Generated by Django 5.1.2 on 2025-08-02

from django.db import migrations, models


def copy_station_stream_order_to_new_order(apps, schema_editor):
    """Copy station_stream_order values to the new order field, rounding to nearest integer."""
    StationStreams = apps.get_model('radio_crestin', 'StationStreams')

    for stream in StationStreams.objects.all():
        stream.order = round(stream.station_stream_order) if stream.station_stream_order is not None else 0
        stream.save(update_fields=['order'])


def reverse_copy_order_to_station_stream_order(apps, schema_editor):
    """Reverse operation: copy order back to station_stream_order as float."""
    StationStreams = apps.get_model('radio_crestin', 'StationStreams')

    for stream in StationStreams.objects.all():
        stream.station_stream_order = float(stream.order)
        stream.save(update_fields=['station_stream_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0018_alter_stations_email'),
    ]

    operations = [
        # Step 1: Rename the existing order field to station_stream_order
        migrations.RenameField(
            model_name='stationstreams',
            old_name='order',
            new_name='station_stream_order',
        ),
        # Step 2: Ensure station_stream_order is a FloatField (it already is, but let's be explicit)
        migrations.AlterField(
            model_name='stationstreams',
            name='station_stream_order',
            field=models.FloatField(verbose_name='Station Stream Order', blank=True, null=True, default=0),
        ),
        # Step 3: Add the new order field as IntegerField
        migrations.AddField(
            model_name='stationstreams',
            name='order',
            field=models.IntegerField(verbose_name='Order', default=0),
        ),
        # Step 4: Copy data from station_stream_order to order (rounded)
        migrations.RunPython(
            copy_station_stream_order_to_new_order,
            reverse_copy_order_to_station_stream_order
        ),
        # Step 5: Update the model meta ordering
        migrations.AlterModelOptions(
            name='stationstreams',
            options={'managed': True, 'ordering': ('station', 'order'), 'verbose_name': 'Station Stream', 'verbose_name_plural': 'Station Streams'},
        ),
    ]
