# Generated by Django 5.1.11 on 2025-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0019_rename_station_to_station_group_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationsuptime',
            name='latency_ms',
            field=models.IntegerField(blank=True, default=-1, verbose_name='Latency (ms)'),
        ),
    ]
