# Generated by Django 5.1.2 on 2025-08-02

from django.db import migrations, models


def copy_station_to_station_group_order_to_new_order(apps, schema_editor):
    """Copy station_to_station_group_order values to the new order field, rounding to nearest integer."""
    StationToStationGroup = apps.get_model('radio_crestin', 'StationToStationGroup')

    for relation in StationToStationGroup.objects.all():
        relation.order = round(relation.station_to_station_group_order) if relation.station_to_station_group_order is not None else 0
        relation.save(update_fields=['order'])


def reverse_copy_order_to_station_to_station_group_order(apps, schema_editor):
    """Reverse operation: copy order back to station_to_station_group_order as float."""
    StationToStationGroup = apps.get_model('radio_crestin', 'StationToStationGroup')

    for relation in StationToStationGroup.objects.all():
        relation.station_to_station_group_order = float(relation.order)
        relation.save(update_fields=['station_to_station_group_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0020_alter_stationsuptime_latency_ms'),
    ]

    operations = [
        # Step 1: Rename the existing order field to station_to_station_group_order
        migrations.RenameField(
            model_name='stationtostationgroup',
            old_name='order',
            new_name='station_to_station_group_order',
        ),
        # Step 2: Ensure station_to_station_group_order is a FloatField
        migrations.AlterField(
            model_name='stationtostationgroup',
            name='station_to_station_group_order',
            field=models.FloatField(verbose_name='Station to Station Group Order', blank=True, null=True, default=0),
        ),
        # Step 3: Add the new order field as IntegerField
        migrations.AddField(
            model_name='stationtostationgroup',
            name='order',
            field=models.IntegerField(verbose_name='Order', default=0),
        ),
        # Step 4: Copy data from station_to_station_group_order to order (rounded)
        migrations.RunPython(
            copy_station_to_station_group_order_to_new_order,
            reverse_copy_order_to_station_to_station_group_order
        ),
        # Step 5: Update the model meta ordering
        migrations.AlterModelOptions(
            name='stationtostationgroup',
            options={'managed': True, 'ordering': ('group',), 'verbose_name': 'Station to Group Relationship', 'verbose_name_plural': 'Station to Group Relationships'},
        ),
    ]
