# Generated by Django 5.1.11 on 2025-08-04 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0021_rename_station_to_station_group_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationsuptime',
            name='latency_ms',
            field=models.IntegerField(default=-1, verbose_name='Latency (ms)'),
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, help_text='Unique identifier for the share link', max_length=10, unique=True)),
                ('visit_count', models.PositiveIntegerField(default=0, help_text='Number of unique visits to this share link')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the share link was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the share link was updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the share link is active')),
                ('station', models.ForeignKey(blank=True, help_text='Optional station to link to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='radio_crestin.stations')),
                ('user', models.ForeignKey(help_text='User who created the share link', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='radio_crestin.appusers')),
            ],
            options={
                'db_table': 'share_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLinkVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the visitor', null=True)),
                ('visitor_user_agent', models.TextField(blank=True, help_text='User agent string of the visitor', null=True)),
                ('visitor_referer', models.URLField(blank=True, help_text='Referer URL if available', max_length=500, null=True)),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the visit occurred')),
                ('visitor_session_id', models.CharField(blank=True, db_index=True, help_text='Session ID to track unique visitors', max_length=100, null=True)),
                ('share_link', models.ForeignKey(help_text='The share link that was visited', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='radio_crestin.sharelink')),
            ],
            options={
                'db_table': 'share_link_visits',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['share_id', 'is_active'], name='share_links_share_i_c280d1_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['user', '-created_at'], name='share_links_user_id_7e64ed_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelinkvisit',
            index=models.Index(fields=['share_link', '-visited_at'], name='share_link__share_l_e0cd24_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelinkvisit',
            index=models.Index(fields=['visitor_session_id', 'share_link'], name='share_link__visitor_e4ab0b_idx'),
        ),
    ]
