# Generated by Django 5.1.11 on 2025-08-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0022_alter_stationsuptime_latency_ms_sharelink_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sharelink',
            name='share_links_user_id_7e64ed_idx',
        ),
        migrations.RemoveField(
            model_name='sharelink',
            name='station',
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='user',
            field=models.OneToOneField(help_text='User who owns this unique share link', on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='radio_crestin.appusers'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['user'], name='share_links_user_id_e1b28d_idx'),
        ),
    ]
