# Generated by Django 5.1.11 on 2025-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0024_set_random_uuid_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
