# Generated by Django 5.1.15 on 2026-01-01 16:46

import superapp.apps.storage.config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0026_clean_invalid_song_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=superapp.apps.storage.config.PublicS3Storage, upload_to='artists/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=superapp.apps.storage.config.PublicS3Storage, upload_to='songs/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='station_order',
            field=models.FloatField(default=0, verbose_name='Station Order'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=superapp.apps.storage.config.PublicS3Storage, upload_to='stations/', verbose_name='Thumbnail'),
        ),
    ]
