# Generated by Django 5.1.15 on 2026-01-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0028_remove_duplicate_anonymous_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stations',
            options={'managed': True, 'ordering': ('station_order', 'title'), 'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
        migrations.AlterModelOptions(
            name='stationstreams',
            options={'managed': True, 'ordering': ('station', 'station_stream_order'), 'verbose_name': 'Station Stream', 'verbose_name_plural': 'Station Streams'},
        ),
        migrations.AlterField(
            model_name='appusers',
            name='anonymous_id',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
