# Generated by Django 5.1.15 on 2026-01-01 19:05

import django.db.models.deletion
from django.db import migrations, models


def clean_orphaned_user_references(apps, schema_editor):
    """
    Set user_id to NULL for any reviews where the user doesn't exist.
    This handles data integrity issues before altering the foreign key.
    """
    # Use raw SQL to avoid loading models that might have changed
    schema_editor.execute("""
        UPDATE reviews
        SET user_id = NULL
        WHERE user_id IS NOT NULL
        AND user_id NOT IN (SELECT id FROM app_users)
    """)


def deduplicate_reviews_by_station(apps, schema_editor):
    """
    For existing reviews that will have the same default IP (0.0.0.0),
    keep only the most recent one per station to avoid unique constraint violation.
    """
    # Delete older duplicate reviews, keeping only the most recent per station
    schema_editor.execute("""
        DELETE FROM reviews
        WHERE id NOT IN (
            SELECT DISTINCT ON (station_id) id
            FROM reviews
            ORDER BY station_id, created_at DESC
        )
    """)


def noop(apps, schema_editor):
    """No-op for reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0029_add_unique_constraint_to_anonymous_id'),
    ]

    operations = [
        # First, remove unique_together constraint
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together=set(),
        ),
        # First, drop the existing foreign key constraint to allow NULL
        migrations.RunSQL(
            sql="ALTER TABLE reviews DROP CONSTRAINT IF EXISTS reviews_user_id_c23b0903_fk_app_users_id;",
            reverse_sql="-- No reverse needed, will be recreated"
        ),
        # Make user_id column nullable
        migrations.RunSQL(
            sql="ALTER TABLE reviews ALTER COLUMN user_id DROP NOT NULL;",
            reverse_sql="ALTER TABLE reviews ALTER COLUMN user_id SET NOT NULL;"
        ),
        # Now clean up orphaned user references
        migrations.RunPython(clean_orphaned_user_references, noop),
        # Re-add the foreign key constraint (now allowing NULL)
        migrations.RunSQL(
            sql="""
                ALTER TABLE reviews
                ADD CONSTRAINT reviews_user_id_c23b0903_fk_app_users_id
                FOREIGN KEY (user_id) REFERENCES app_users(id)
                ON DELETE SET NULL
                DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="-- No reverse needed"
        ),
        migrations.AddField(
            model_name='reviews',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', help_text='IP address of the reviewer', verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_identifier',
            field=models.CharField(blank=True, help_text='Unique identifier sent by the client (e.g., device ID, anonymous ID)', max_length=255, null=True, verbose_name='User Identifier'),
        ),
        # Deduplicate reviews before adding unique constraint
        migrations.RunPython(deduplicate_reviews_by_station, noop),
        # Update the Django state for the user field
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radio_reviews', to='radio_crestin.appusers', verbose_name='App User'),
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('station', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['station', 'ip_address'], name='reviews_station_849d01_idx'),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['user_identifier'], name='reviews_user_id_c0cdf4_idx'),
        ),
    ]
