# Generated by Django 5.1.15 on 2026-01-01 19:19

import superapp.apps.storage.config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0030_add_ip_and_user_identifier_to_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=superapp.apps.storage.config.get_public_storage, upload_to='artists/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=superapp.apps.storage.config.get_public_storage, upload_to='songs/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=superapp.apps.storage.config.get_public_storage, upload_to='stations/', verbose_name='Thumbnail'),
        ),
    ]
