# Generated by Django 5.1.15 on 2026-02-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0031_alter_artists_thumbnail_alter_songs_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='verified',
            field=models.BooleanField(default=True, verbose_name='Verified'),
        ),
        migrations.CreateModel(
            name='StationsNowPlayingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('listeners', models.IntegerField(blank=True, null=True, verbose_name='Listeners')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='played_history', to='radio_crestin.songs', verbose_name='Song')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='now_playing_history', to='radio_crestin.stations', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Station Now Playing History',
                'verbose_name_plural': 'Station Now Playing History',
                'db_table': 'stations_now_playing_history',
                'ordering': ('-timestamp',),
                'managed': True,
                'indexes': [models.Index(fields=['station', '-timestamp'], name='idx_snph_station_ts'), models.Index(fields=['timestamp', 'station'], name='idx_snph_ts_station')],
            },
        ),
    ]
