# Generated by Django 5.1.15 on 2026-04-07 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0032_alter_reviews_verified_stationsnowplayinghistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviews',
            name='song',
            field=models.ForeignKey(blank=True, help_text='Optional song being reviewed. If set, allows a separate review per song.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='radio_crestin.songs', verbose_name='Song'),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['song'], name='reviews_song_id_1ade62_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(condition=models.Q(('song__isnull', True)), fields=('station', 'ip_address'), name='unique_review_station_ip_no_song'),
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(condition=models.Q(('song__isnull', False)), fields=('station', 'ip_address', 'song'), name='unique_review_station_ip_song'),
        ),
    ]
