# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0033_add_song_to_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningsessions',
            name='referer',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Referer'),
        ),
    ]
