# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0034_alter_listeningsessions_referer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stations',
            old_name='generate_hls_stream',
            new_name='transcode_enabled',
        ),
    ]
