# Generated by Django 5.1.15 on 2026-04-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0037_add_mel_analysis_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='transcode_enabled',
            field=models.BooleanField(default=True, verbose_name='Live Transcoding'),
        ),
        migrations.CreateModel(
            name='HlsSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codec', models.CharField(default='aac', help_text='Codec identifier (aac, opus)', max_length=10, verbose_name='Codec')),
                ('segment_number', models.BigIntegerField(help_text='Epoch-based segment identifier (filename without extension)', verbose_name='Segment Number')),
                ('duration', models.FloatField(default=6.0, help_text='Segment duration in seconds', verbose_name='Duration')),
                ('program_date_time', models.DateTimeField(blank=True, help_text='ISO 8601 timestamp for EXT-X-PROGRAM-DATE-TIME', null=True, verbose_name='Program Date Time')),
                ('is_on_disk', models.BooleanField(default=True, help_text="Whether the segment is currently on the pod's local disk", verbose_name='On Disk')),
                ('is_on_s3', models.BooleanField(default=False, help_text='Whether the segment has been uploaded to S3', verbose_name='On S3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hls_segments', to='radio_crestin.stations', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'HLS Segment',
                'verbose_name_plural': 'HLS Segments',
                'db_table': 'hls_segments',
                'ordering': ('station', 'codec', 'segment_number'),
                'managed': True,
                'indexes': [models.Index(fields=['station', 'codec', 'segment_number'], name='idx_hls_seg_station_codec_num'), models.Index(fields=['station', 'codec', '-segment_number'], name='idx_hls_seg_latest'), models.Index(fields=['station', 'codec', 'is_on_disk'], name='idx_hls_seg_disk')],
                'constraints': [models.UniqueConstraint(fields=('station', 'codec', 'segment_number'), name='uq_hls_segment')],
            },
        ),
    ]
