# Generated by Django 5.1.15 on 2026-04-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_crestin', '0038_create_hls_segments'),
    ]

    operations = [
        migrations.CreateModel(
            name='HlsEncodingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codec', models.CharField(default='aac', max_length=10, verbose_name='Codec')),
                ('start_epoch', models.BigIntegerField(help_text='First aligned segment epoch in this session', verbose_name='Start Epoch')),
                ('end_epoch', models.BigIntegerField(help_text='Last known segment epoch (updated by heartbeat)', verbose_name='End Epoch')),
                ('segment_duration', models.IntegerField(default=6, verbose_name='Segment Duration')),
                ('pod_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Pod Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hls_encoding_sessions', to='radio_crestin.stations', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'HLS Encoding Session',
                'verbose_name_plural': 'HLS Encoding Sessions',
                'db_table': 'hls_encoding_sessions',
                'ordering': ('station', 'codec', 'start_epoch'),
                'managed': True,
                'indexes': [models.Index(fields=['station', 'codec', 'start_epoch'], name='idx_hls_sess_station_codec')],
                'constraints': [models.UniqueConstraint(fields=('station', 'codec', 'start_epoch'), name='uq_hls_encoding_session')],
            },
        ),
    ]
