version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.33.4.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
