-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."station_groups" add column "order" numeric
--  not null default '0';
