apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stream-controller
  namespace: radio-crestin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stream-controller
subjects:
  - kind: ServiceAccount
    name: stream-controller
    namespace: radio-crestin
