"""
Django settings for superapp project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import warnings
from os import environ
from pathlib import Path

from django.core.cache.backends.base import CacheKeyWarning

# Suppress CacheKeyWarning: strawberry-django's DjangoValidationCache generates
# long cache keys with special chars. This is harmless with Redis (not memcached).
warnings.filterwarnings("ignore", category=CacheKeyWarning)

import dj_database_url
from django.core.management.utils import get_random_secret_key
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ROOT_DIR = Path(__file__).resolve().parent.parent.parent

SECRET_KEY = environ.get("SECRET_KEY", get_random_secret_key())

DEBUG = environ.get("DEBUG", 'false') == 'true'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

ALLOWED_HOSTS = environ.get("ALLOWED_HOSTS", "").split(",") + ['localhost', '127.0.0.1']
ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host.strip()]
if DEBUG:
    ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = environ.get(
    "CSRF_TRUSTED_ORIGINS", ""
).split(",") + ['http://localhost:8080', 'http://localhost:3000']
CSRF_TRUSTED_ORIGINS = [host for host in CSRF_TRUSTED_ORIGINS if host.strip()]

######################################################################
# Apps
######################################################################
INSTALLED_APPS = [
    "storages",
    "django_superapp",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
]

######################################################################
# Middleware
######################################################################
MIDDLEWARE = [
    "django.middleware.cache.UpdateCacheMiddleware",         # Must be first — stores responses in cache
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    *(["debug_toolbar.middleware.DebugToolbarMiddleware"] if DEBUG else []),
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.cache.FetchFromCacheMiddleware",      # Must be last — serves from cache
]

# Server-side cache: use s-maxage from Cache-Control headers.
# Fallback TTL for responses without explicit cache headers.
CACHE_MIDDLEWARE_SECONDS = 0
CACHE_MIDDLEWARE_KEY_PREFIX = "page"

######################################################################
# Sessions
######################################################################
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

ROOT_URLCONF = 'superapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'superapp' / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'superapp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    "default": {
        **dj_database_url.config(default=os.environ.get('DATABASE_URL')),
        "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", 0)),
        "CONN_HEALTH_CHECKS": True,
    },
    # Direct connection bypassing PgBouncer - required for operations that use
    # server-side cursors (e.g. dumpdata), which are incompatible with
    # PgBouncer's transaction pooling mode.
    "direct": {
        **dj_database_url.parse(
            os.environ.get('DATABASE_DIRECT_URL')
            or os.environ.get('DATABASE_URL', '').replace('-pooler-rw', '-rw')
        ),
        "CONN_MAX_AGE": 0,
        "CONN_HEALTH_CHECKS": True,
    },
} if os.environ.get('DATABASE_URL', '') != '' else {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

######################################################################
# Caches
######################################################################
CACHES = {
    'default': {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get('REDIS_BROKER_URL'),
        "TIMEOUT": 3600,  # 1 hour max TTL for all cache entries
    }
} if os.environ.get('REDIS_BROKER_URL', '') != '' else {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': 3600,
    }
}

# Always log to console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'formatters': {
        'verbose': {
            'format': '[contactor] %(levelname)s %(asctime)s %(message)s'
        },
    },
    'handlers': {
        # Send all messages to console
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
        # Send info messages to syslog
        # 'syslog': {
        #     'level': 'INFO',
        #     'class': 'logging.handlers.SysLogHandler',
        #     'facility': SysLogHandler.LOG_LOCAL2,
        #     'address': '/dev/log',
        #     'formatter': 'verbose',
        # },
        # Warning messages are sent to admin emails
        'mail_admins': {
            'level': 'WARNING',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'loggers': {
        # This is the "catch all" logger
        '': {
            'handlers': ['console', 'mail_admins', ],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        # Suppress noisy boto3/botocore debug logs (S3 event handlers, endpoint resolution)
        'boto3': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'botocore': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        's3transfer': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'urllib3': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    }
}

######################################################################
# Localization
######################################################################
LANGUAGE_CODE = "en"

TIME_ZONE = "Europe/Berlin"

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = (
    ("en", _("English")),
    ("ro", _("Română")),
    ("de", _("German")),
)
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]
LANGUAGE_COOKIE_NAME = 'django_language'

######################################################################
# Static
######################################################################
STATIC_URL = "/static/"

STATICFILES_DIRS = [BASE_DIR / "superapp" / "static"]

STATIC_ROOT = BASE_DIR / "superapp" / "staticfiles"

MEDIA_ROOT = BASE_DIR / "media"

MEDIA_URL = "/media/"

############################################################################
# Debug toolbar
############################################################################
DEBUG_TOOLBAR_CONFIG = {"SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG}

######################################################################
# X_FRAME
######################################################################
X_FRAME_OPTIONS = "SAMEORIGIN"

######################################################################
# STORAGE
######################################################################

if environ.get("AWS_ACCESS_KEY_ID"):
    AWS_ACCESS_KEY_ID = environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_ENDPOINT_URL = environ.get("AWS_ENDPOINT_URL")
    AWS_S3_SIGNATURE_VERSION = environ.get("AWS_S3_SIGNATURE_VERSION")
    AWS_S3_ADDRESSING_STYLE = environ.get("AWS_S3_ADDRESSING_STYLE")
    AWS_S3_CUSTOM_DOMAIN = environ.get("AWS_S3_CUSTOM_DOMAIN")
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "querystring_auth": False,
                "default_acl": "public-read",
            },
        } if not DEBUG else {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
            "OPTIONS": {},
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
            "OPTIONS": {},
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
            "OPTIONS": {},
        },
    }
######################################################################
# CDN Image Proxy
######################################################################
CDN_SIGNING_SECRET = environ.get('CDN_SIGNING_SECRET', '')

######################################################################
# SUPERAPP dynamic settings and urls
######################################################################
from django_superapp.settings import extend_superapp_settings
from . import apps as superapp_apps

extend_superapp_settings(
    main_settings=globals(),
    superapp_apps=superapp_apps
)
