# Generated by Django 5.1.6 on 2025-02-06 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='user_accounts', to='authentication.account'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='user_sessions', to='authentication.session'),
        ),
        migrations.AlterUniqueTogether(
            name='verificationtoken',
            unique_together={('identifier', 'token')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('provider', 'provider_account_id')},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('anonymous_id', None), _negated=True), fields=('anonymous_id',), name='unique_anonymous_id'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email', None), _negated=True), fields=('email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number', None), _negated=True), fields=('phone_number',), name='unique_phone_number'),
        ),
    ]
