# Generated by Django 5.1.6 on 2025-02-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sessions',
        ),
        migrations.DeleteModel(
            name='VerificationToken',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
