# Generated by Django 5.1.11 on 2025-07-21 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radio_crestin', '0007_alter_songs_unique_together_alter_songs_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationScrapingTaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Task ID')),
                ('current_task_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Current Task Started At')),
                ('processed_fetcher_states', models.JSONField(default=dict, help_text='JSON tracking state of each fetcher: {fetcher_id: {status, priority, data, timestamp}}', verbose_name='Processed Fetcher States')),
                ('last_successful_update_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Successful Update At')),
                ('last_successful_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Successful Task ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_task_state', to='radio_crestin.stations', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Station Scraping Task State',
                'verbose_name_plural': 'Station Scraping Task States',
                'db_table': 'station_scraping_task_states',
            },
        ),
    ]
