-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."stations" add column "feature_latest_post" boolean
--  not null default 'true';
